Added check to check for different locations of g++

diff --git a/_bash-c-course-rc b/_bash-c-course-rc
--- a/_bash-c-course-rc
+++ b/_bash-c-course-rc
@@ -1,9 +1,17 @@
 # This is a bash snippet, to be sourced from .profile
 # NB Do not source this snippet multiple times. It'll clutter your environment.
+if [ -x /usr/local/bin/g++ ] ; then
+    GCCBASE="/usr/local"
+elif [ -x /usr/bin/g++ ] ; then
+    GCCBASE="/usr"
+else
+    echo "Could not find g++ "
+    exit 1
+fi
 
-GCCBASE="/usr/local"
-
-# Find all dirs containing libraries
+echo $GCCBASE
+# Find all dirs containing libraries.
+# TODO: This search is a bit expensive.
 LIBDIRS="$(find ${GCCBASE} -iname \*\.so\.\* -exec dirname {} \;|sort |uniq|grep -v 32$|tr '\n' ':')"
 
 # If you want the newer tools by default, put them at the beginning of $PATH
